/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
export type PostAuthSignInBody = {
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  password: string;
};

export type PostAuthSignIn200DataUser = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$ */
  id: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  name: string;
};

export type PostAuthSignIn200Data = {
  accessToken: string;
  refreshToken: string;
  user: PostAuthSignIn200DataUser;
};

export type PostAuthSignIn200Meta = {
  unixTimestamp: number;
  requestId?: string;
};

export type PostAuthSignIn200 = {
  success: true;
  data: PostAuthSignIn200Data;
  error: unknown | null;
  meta: PostAuthSignIn200Meta;
};

export type PostAuthSignIn400Error = {
  code: string;
  details?: unknown;
};

export type PostAuthSignIn400Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Invalid input or missing required fields
 */
export type PostAuthSignIn400 = {
  success: false;
  data: unknown | null;
  error: PostAuthSignIn400Error;
  meta: PostAuthSignIn400Meta;
};

export type PostAuthSignIn401Error = {
  code: string;
  details?: unknown;
};

export type PostAuthSignIn401Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Invalid username or password
 */
export type PostAuthSignIn401 = {
  success: false;
  data: unknown | null;
  error: PostAuthSignIn401Error;
  meta: PostAuthSignIn401Meta;
};

export type PostAuthSignUpBody = {
  /**
   * @minLength 2
   * @maxLength 20
   */
  name: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  password: string;
};

export type PostAuthSignUp201Data = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$ */
  id: string;
};

export type PostAuthSignUp201Meta = {
  unixTimestamp: number;
  requestId?: string;
};

export type PostAuthSignUp201 = {
  success: true;
  data: PostAuthSignUp201Data;
  error: unknown | null;
  meta: PostAuthSignUp201Meta;
};

export type PostAuthSignUp400Error = {
  code: string;
  details?: unknown;
};

export type PostAuthSignUp400Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Invalid input or missing required fields
 */
export type PostAuthSignUp400 = {
  success: false;
  data: unknown | null;
  error: PostAuthSignUp400Error;
  meta: PostAuthSignUp400Meta;
};

export type PostAuthSignUp409Error = {
  code: string;
  details?: unknown;
};

export type PostAuthSignUp409Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * User already exists
 */
export type PostAuthSignUp409 = {
  success: false;
  data: unknown | null;
  error: PostAuthSignUp409Error;
  meta: PostAuthSignUp409Meta;
};

export type PostAuthSignOutBody = { [key: string]: unknown };

export type PostAuthSignOut200Data = { [key: string]: unknown };

export type PostAuthSignOut200Meta = {
  unixTimestamp: number;
  requestId?: string;
};

export type PostAuthSignOut200 = {
  success: true;
  data: PostAuthSignOut200Data;
  error: unknown | null;
  meta: PostAuthSignOut200Meta;
};

export type PostAuthSignOut401Error = {
  code: string;
  details?: unknown;
};

export type PostAuthSignOut401Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Invalid refreshToken
 */
export type PostAuthSignOut401 = {
  success: false;
  data: unknown | null;
  error: PostAuthSignOut401Error;
  meta: PostAuthSignOut401Meta;
};

export type PostAuthRefreshBody = { [key: string]: unknown };

export type PostAuthRefresh200DataUser = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$ */
  id: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  name: string;
};

export type PostAuthRefresh200Data = {
  accessToken: string;
  refreshToken: string;
  user: PostAuthRefresh200DataUser;
};

export type PostAuthRefresh200Meta = {
  unixTimestamp: number;
  requestId?: string;
};

export type PostAuthRefresh200 = {
  success: true;
  data: PostAuthRefresh200Data;
  error: unknown | null;
  meta: PostAuthRefresh200Meta;
};

export type PostAuthRefresh401Error = {
  code: string;
  details?: unknown;
};

export type PostAuthRefresh401Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Invalid refreshToken
 */
export type PostAuthRefresh401 = {
  success: false;
  data: unknown | null;
  error: PostAuthRefresh401Error;
  meta: PostAuthRefresh401Meta;
};

export type PostAuthRefresh404Error = {
  code: string;
  details?: unknown;
};

export type PostAuthRefresh404Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Session Not Found
 */
export type PostAuthRefresh404 = {
  success: false;
  data: unknown | null;
  error: PostAuthRefresh404Error;
  meta: PostAuthRefresh404Meta;
};

export type PostOrganizationBody = {
  /**
   * @minLength 1
   * @maxLength 20
   */
  title: string;
};

export type PostOrganization201Data = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$ */
  id: string;
  title: string;
};

export type PostOrganization201Meta = {
  unixTimestamp: number;
  requestId?: string;
};

export type PostOrganization201 = {
  success: true;
  data: PostOrganization201Data;
  error: unknown | null;
  meta: PostOrganization201Meta;
};

export type PostOrganization401Error = {
  code: string;
  details?: unknown;
};

export type PostOrganization401Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Access token verification failed.
 */
export type PostOrganization401 = {
  success: false;
  data: unknown | null;
  error: PostOrganization401Error;
  meta: PostOrganization401Meta;
};

export type PostOrganization404Error = {
  code: string;
  details?: unknown;
};

export type PostOrganization404Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Invalid data or missing required fields
 */
export type PostOrganization404 = {
  success: false;
  data: unknown | null;
  error: PostOrganization404Error;
  meta: PostOrganization404Meta;
};

export type PostOrganization409Error = {
  code: string;
  details?: unknown;
};

export type PostOrganization409Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Organization name already exists
 */
export type PostOrganization409 = {
  success: false;
  data: unknown | null;
  error: PostOrganization409Error;
  meta: PostOrganization409Meta;
};

export type GetOrganization200DataItemUserRole =
  (typeof GetOrganization200DataItemUserRole)[keyof typeof GetOrganization200DataItemUserRole];

export const GetOrganization200DataItemUserRole = {
  ADMIN: 'ADMIN',
  MAINTAINER: 'MAINTAINER',
  MEMBER: 'MEMBER',
} as const;

export type GetOrganization200DataItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$ */
  id: string;
  title: string;
  userRole: GetOrganization200DataItemUserRole;
  memberCount: number;
};

export type GetOrganization200Meta = {
  unixTimestamp: number;
  requestId?: string;
};

export type GetOrganization200 = {
  success: true;
  data: GetOrganization200DataItem[];
  error: unknown | null;
  meta: GetOrganization200Meta;
};

export type GetOrganization401Error = {
  code: string;
  details?: unknown;
};

export type GetOrganization401Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Access token verification failed.
 */
export type GetOrganization401 = {
  success: false;
  data: unknown | null;
  error: GetOrganization401Error;
  meta: GetOrganization401Meta;
};

export type PostOrganizationByOrganizationIdInvitationsBodyRole =
  (typeof PostOrganizationByOrganizationIdInvitationsBodyRole)[keyof typeof PostOrganizationByOrganizationIdInvitationsBodyRole];

export const PostOrganizationByOrganizationIdInvitationsBodyRole = {
  ADMIN: 'ADMIN',
  MAINTAINER: 'MAINTAINER',
  MEMBER: 'MEMBER',
} as const;

export type PostOrganizationByOrganizationIdInvitationsBody = {
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  role: PostOrganizationByOrganizationIdInvitationsBodyRole;
};

export type PostOrganizationByOrganizationIdInvitations201Meta = {
  unixTimestamp: number;
  requestId?: string;
};

export type PostOrganizationByOrganizationIdInvitations201 = {
  success: true;
  data: unknown | null;
  error: unknown | null;
  meta: PostOrganizationByOrganizationIdInvitations201Meta;
};

export type PostOrganizationByOrganizationIdInvitations401Error = {
  code: string;
  details?: unknown;
};

export type PostOrganizationByOrganizationIdInvitations401Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Access token verification failed.
 */
export type PostOrganizationByOrganizationIdInvitations401 = {
  success: false;
  data: unknown | null;
  error: PostOrganizationByOrganizationIdInvitations401Error;
  meta: PostOrganizationByOrganizationIdInvitations401Meta;
};

export type PostOrganizationByOrganizationIdInvitations404Error = {
  code: string;
  details?: unknown;
};

export type PostOrganizationByOrganizationIdInvitations404Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Invalid data or missing required fields
 */
export type PostOrganizationByOrganizationIdInvitations404 = {
  success: false;
  data: unknown | null;
  error: PostOrganizationByOrganizationIdInvitations404Error;
  meta: PostOrganizationByOrganizationIdInvitations404Meta;
};

export type PostOrganizationByOrganizationIdInvitations409Error = {
  code: string;
  details?: unknown;
};

export type PostOrganizationByOrganizationIdInvitations409Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Invitee is wrong
 */
export type PostOrganizationByOrganizationIdInvitations409 = {
  success: false;
  data: unknown | null;
  error: PostOrganizationByOrganizationIdInvitations409Error;
  meta: PostOrganizationByOrganizationIdInvitations409Meta;
};

export type PostOrganizationByOrganizationIdInvitations422Error = {
  code: string;
  details?: unknown;
};

export type PostOrganizationByOrganizationIdInvitations422Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Invalid data
 */
export type PostOrganizationByOrganizationIdInvitations422 = {
  success: false;
  data: unknown | null;
  error: PostOrganizationByOrganizationIdInvitations422Error;
  meta: PostOrganizationByOrganizationIdInvitations422Meta;
};

export type GetOrganizationByOrganizationIdInvitations200DataItemInvitee =
  | {
      /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$ */
      id: string;
      name: string;
      /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
      email: string;
    }
  | unknown
  | null;

export type GetOrganizationByOrganizationIdInvitations200DataItemRole =
  (typeof GetOrganizationByOrganizationIdInvitations200DataItemRole)[keyof typeof GetOrganizationByOrganizationIdInvitations200DataItemRole];

export const GetOrganizationByOrganizationIdInvitations200DataItemRole = {
  ADMIN: 'ADMIN',
  MAINTAINER: 'MAINTAINER',
  MEMBER: 'MEMBER',
} as const;

export type GetOrganizationByOrganizationIdInvitations200DataItemStatus =
  (typeof GetOrganizationByOrganizationIdInvitations200DataItemStatus)[keyof typeof GetOrganizationByOrganizationIdInvitations200DataItemStatus];

export const GetOrganizationByOrganizationIdInvitations200DataItemStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  CANCELED: 'CANCELED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED',
} as const;

export type GetOrganizationByOrganizationIdInvitations200DataItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$ */
  organizationId: string;
  invitee: GetOrganizationByOrganizationIdInvitations200DataItemInvitee;
  role: GetOrganizationByOrganizationIdInvitations200DataItemRole;
  status: GetOrganizationByOrganizationIdInvitations200DataItemStatus;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  expiresAt: string;
};

export type GetOrganizationByOrganizationIdInvitations200Meta = {
  unixTimestamp: number;
  requestId?: string;
};

export type GetOrganizationByOrganizationIdInvitations200 = {
  success: true;
  data: GetOrganizationByOrganizationIdInvitations200DataItem[];
  error: unknown | null;
  meta: GetOrganizationByOrganizationIdInvitations200Meta;
};

export type GetOrganizationByOrganizationIdInvitations401Error = {
  code: string;
  details?: unknown;
};

export type GetOrganizationByOrganizationIdInvitations401Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Access token verification failed.
 */
export type GetOrganizationByOrganizationIdInvitations401 = {
  success: false;
  data: unknown | null;
  error: GetOrganizationByOrganizationIdInvitations401Error;
  meta: GetOrganizationByOrganizationIdInvitations401Meta;
};

export type PatchOrganizationInvitationBodyStatus =
  (typeof PatchOrganizationInvitationBodyStatus)[keyof typeof PatchOrganizationInvitationBodyStatus];

export const PatchOrganizationInvitationBodyStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  CANCELED: 'CANCELED',
  REJECTED: 'REJECTED',
} as const;

export type PatchOrganizationInvitationBody = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$ */
  invitationId: string;
  status: PatchOrganizationInvitationBodyStatus;
};

export type PatchOrganizationInvitation200Meta = {
  unixTimestamp: number;
  requestId?: string;
};

export type PatchOrganizationInvitation200 = {
  success: true;
  data: unknown | null;
  error: unknown | null;
  meta: PatchOrganizationInvitation200Meta;
};

export type PatchOrganizationInvitation401Error = {
  code: string;
  details?: unknown;
};

export type PatchOrganizationInvitation401Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Access token verification failed.
 */
export type PatchOrganizationInvitation401 = {
  success: false;
  data: unknown | null;
  error: PatchOrganizationInvitation401Error;
  meta: PatchOrganizationInvitation401Meta;
};

export type PatchOrganizationInvitation403Error = {
  code: string;
  details?: unknown;
};

export type PatchOrganizationInvitation403Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Wrong Invitee or Invited User
 */
export type PatchOrganizationInvitation403 = {
  success: false;
  data: unknown | null;
  error: PatchOrganizationInvitation403Error;
  meta: PatchOrganizationInvitation403Meta;
};

export type PatchOrganizationInvitation404Error = {
  code: string;
  details?: unknown;
};

export type PatchOrganizationInvitation404Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Invalid data or missing required fields
 */
export type PatchOrganizationInvitation404 = {
  success: false;
  data: unknown | null;
  error: PatchOrganizationInvitation404Error;
  meta: PatchOrganizationInvitation404Meta;
};

export type PatchOrganizationInvitation422Error = {
  code: string;
  details?: unknown;
};

export type PatchOrganizationInvitation422Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Invalid data
 */
export type PatchOrganizationInvitation422 = {
  success: false;
  data: unknown | null;
  error: PatchOrganizationInvitation422Error;
  meta: PatchOrganizationInvitation422Meta;
};

export type GetOrganizationInvitations200DataItemOrganization = {
  id: string;
  title: string;
};

export type GetOrganizationInvitations200DataItemInvitedBy =
  | {
      /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$ */
      id: string;
      name: string;
      /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
      email: string;
    }
  | unknown
  | null;

export type GetOrganizationInvitations200DataItemRole =
  (typeof GetOrganizationInvitations200DataItemRole)[keyof typeof GetOrganizationInvitations200DataItemRole];

export const GetOrganizationInvitations200DataItemRole = {
  ADMIN: 'ADMIN',
  MAINTAINER: 'MAINTAINER',
  MEMBER: 'MEMBER',
} as const;

export type GetOrganizationInvitations200DataItemStatus =
  (typeof GetOrganizationInvitations200DataItemStatus)[keyof typeof GetOrganizationInvitations200DataItemStatus];

export const GetOrganizationInvitations200DataItemStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  CANCELED: 'CANCELED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED',
} as const;

export type GetOrganizationInvitations200DataItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$ */
  id: string;
  organization: GetOrganizationInvitations200DataItemOrganization;
  invitedBy: GetOrganizationInvitations200DataItemInvitedBy;
  role: GetOrganizationInvitations200DataItemRole;
  status: GetOrganizationInvitations200DataItemStatus;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  expiresAt: string;
};

export type GetOrganizationInvitations200Meta = {
  unixTimestamp: number;
  requestId?: string;
};

export type GetOrganizationInvitations200 = {
  success: true;
  data: GetOrganizationInvitations200DataItem[];
  error: unknown | null;
  meta: GetOrganizationInvitations200Meta;
};

export type GetOrganizationInvitations401Error = {
  code: string;
  details?: unknown;
};

export type GetOrganizationInvitations401Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Access token verification failed.
 */
export type GetOrganizationInvitations401 = {
  success: false;
  data: unknown | null;
  error: GetOrganizationInvitations401Error;
  meta: GetOrganizationInvitations401Meta;
};

export type GetUserMe200Data = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$ */
  id: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  name: string;
};

export type GetUserMe200Meta = {
  unixTimestamp: number;
  requestId?: string;
};

export type GetUserMe200 = {
  success: true;
  data: GetUserMe200Data;
  error: unknown | null;
  meta: GetUserMe200Meta;
};

export type GetUserMe401Error = {
  code: string;
  details?: unknown;
};

export type GetUserMe401Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Access token verification failed.
 */
export type GetUserMe401 = {
  success: false;
  data: unknown | null;
  error: GetUserMe401Error;
  meta: GetUserMe401Meta;
};

export type GetUserMe404Error = {
  code: string;
  details?: unknown;
};

export type GetUserMe404Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * User not found
 */
export type GetUserMe404 = {
  success: false;
  data: unknown | null;
  error: GetUserMe404Error;
  meta: GetUserMe404Meta;
};

export type GetUserParams = {
  /**
   * @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$
   */
  email: string;
};

export type GetUser200Data = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$ */
  id: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  name: string;
};

export type GetUser200Meta = {
  unixTimestamp: number;
  requestId?: string;
};

export type GetUser200 = {
  success: true;
  data: GetUser200Data;
  error: unknown | null;
  meta: GetUser200Meta;
};

export type GetUser401Error = {
  code: string;
  details?: unknown;
};

export type GetUser401Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Access token verification failed.
 */
export type GetUser401 = {
  success: false;
  data: unknown | null;
  error: GetUser401Error;
  meta: GetUser401Meta;
};

export type GetUser404Error = {
  code: string;
  details?: unknown;
};

export type GetUser404Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * User not found
 */
export type GetUser404 = {
  success: false;
  data: unknown | null;
  error: GetUser404Error;
  meta: GetUser404Meta;
};

export type GetUser422Error = {
  code: string;
  details?: unknown;
};

export type GetUser422Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Invalid query parameters
 */
export type GetUser422 = {
  success: false;
  data: unknown | null;
  error: GetUser422Error;
  meta: GetUser422Meta;
};

export type postAuthSignInResponse200 = {
  data: PostAuthSignIn200;
  status: 200;
};

export type postAuthSignInResponse400 = {
  data: PostAuthSignIn400;
  status: 400;
};

export type postAuthSignInResponse401 = {
  data: PostAuthSignIn401;
  status: 401;
};

export type postAuthSignInResponseSuccess = postAuthSignInResponse200 & {
  headers: Headers;
};
export type postAuthSignInResponseError = (
  | postAuthSignInResponse400
  | postAuthSignInResponse401
) & {
  headers: Headers;
};

export type postAuthSignInResponse =
  | postAuthSignInResponseSuccess
  | postAuthSignInResponseError;

export const getPostAuthSignInUrl = () => {
  return `http://localhost:4000/auth/sign-in`;
};

/**
 * @summary Sign In User
 */
export const postAuthSignIn = async (
  postAuthSignInBody: PostAuthSignInBody,
  options?: RequestInit,
): Promise<postAuthSignInResponse> => {
  const res = await fetch(getPostAuthSignInUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postAuthSignInBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postAuthSignInResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postAuthSignInResponse;
};

export type postAuthSignUpResponse201 = {
  data: PostAuthSignUp201;
  status: 201;
};

export type postAuthSignUpResponse400 = {
  data: PostAuthSignUp400;
  status: 400;
};

export type postAuthSignUpResponse409 = {
  data: PostAuthSignUp409;
  status: 409;
};

export type postAuthSignUpResponseSuccess = postAuthSignUpResponse201 & {
  headers: Headers;
};
export type postAuthSignUpResponseError = (
  | postAuthSignUpResponse400
  | postAuthSignUpResponse409
) & {
  headers: Headers;
};

export type postAuthSignUpResponse =
  | postAuthSignUpResponseSuccess
  | postAuthSignUpResponseError;

export const getPostAuthSignUpUrl = () => {
  return `http://localhost:4000/auth/sign-up`;
};

/**
 * @summary Sign Up User
 */
export const postAuthSignUp = async (
  postAuthSignUpBody: PostAuthSignUpBody,
  options?: RequestInit,
): Promise<postAuthSignUpResponse> => {
  const res = await fetch(getPostAuthSignUpUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postAuthSignUpBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postAuthSignUpResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postAuthSignUpResponse;
};

export type postAuthSignOutResponse200 = {
  data: PostAuthSignOut200;
  status: 200;
};

export type postAuthSignOutResponse401 = {
  data: PostAuthSignOut401;
  status: 401;
};

export type postAuthSignOutResponseSuccess = postAuthSignOutResponse200 & {
  headers: Headers;
};
export type postAuthSignOutResponseError = postAuthSignOutResponse401 & {
  headers: Headers;
};

export type postAuthSignOutResponse =
  | postAuthSignOutResponseSuccess
  | postAuthSignOutResponseError;

export const getPostAuthSignOutUrl = () => {
  return `http://localhost:4000/auth/sign-out`;
};

/**
 * @summary Sign Out
 */
export const postAuthSignOut = async (
  postAuthSignOutBody: PostAuthSignOutBody,
  options?: RequestInit,
): Promise<postAuthSignOutResponse> => {
  const res = await fetch(getPostAuthSignOutUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postAuthSignOutBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postAuthSignOutResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postAuthSignOutResponse;
};

export type postAuthRefreshResponse200 = {
  data: PostAuthRefresh200;
  status: 200;
};

export type postAuthRefreshResponse401 = {
  data: PostAuthRefresh401;
  status: 401;
};

export type postAuthRefreshResponse404 = {
  data: PostAuthRefresh404;
  status: 404;
};

export type postAuthRefreshResponseSuccess = postAuthRefreshResponse200 & {
  headers: Headers;
};
export type postAuthRefreshResponseError = (
  | postAuthRefreshResponse401
  | postAuthRefreshResponse404
) & {
  headers: Headers;
};

export type postAuthRefreshResponse =
  | postAuthRefreshResponseSuccess
  | postAuthRefreshResponseError;

export const getPostAuthRefreshUrl = () => {
  return `http://localhost:4000/auth/refresh`;
};

/**
 * @summary Refresh Auth Token
 */
export const postAuthRefresh = async (
  postAuthRefreshBody: PostAuthRefreshBody,
  options?: RequestInit,
): Promise<postAuthRefreshResponse> => {
  const res = await fetch(getPostAuthRefreshUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postAuthRefreshBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postAuthRefreshResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postAuthRefreshResponse;
};

export type postOrganizationResponse201 = {
  data: PostOrganization201;
  status: 201;
};

export type postOrganizationResponse401 = {
  data: PostOrganization401;
  status: 401;
};

export type postOrganizationResponse404 = {
  data: PostOrganization404;
  status: 404;
};

export type postOrganizationResponse409 = {
  data: PostOrganization409;
  status: 409;
};

export type postOrganizationResponseSuccess = postOrganizationResponse201 & {
  headers: Headers;
};
export type postOrganizationResponseError = (
  | postOrganizationResponse401
  | postOrganizationResponse404
  | postOrganizationResponse409
) & {
  headers: Headers;
};

export type postOrganizationResponse =
  | postOrganizationResponseSuccess
  | postOrganizationResponseError;

export const getPostOrganizationUrl = () => {
  return `http://localhost:4000/organization/`;
};

/**
 * @summary Create Organization
 */
export const postOrganization = async (
  postOrganizationBody: PostOrganizationBody,
  options?: RequestInit,
): Promise<postOrganizationResponse> => {
  const res = await fetch(getPostOrganizationUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postOrganizationBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postOrganizationResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postOrganizationResponse;
};

export type getOrganizationResponse200 = {
  data: GetOrganization200;
  status: 200;
};

export type getOrganizationResponse401 = {
  data: GetOrganization401;
  status: 401;
};

export type getOrganizationResponseSuccess = getOrganizationResponse200 & {
  headers: Headers;
};
export type getOrganizationResponseError = getOrganizationResponse401 & {
  headers: Headers;
};

export type getOrganizationResponse =
  | getOrganizationResponseSuccess
  | getOrganizationResponseError;

export const getGetOrganizationUrl = () => {
  return `http://localhost:4000/organization/`;
};

/**
 * @summary Find User Organizations List
 */
export const getOrganization = async (
  options?: RequestInit,
): Promise<getOrganizationResponse> => {
  const res = await fetch(getGetOrganizationUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getOrganizationResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getOrganizationResponse;
};

export type postOrganizationByOrganizationIdInvitationsResponse201 = {
  data: PostOrganizationByOrganizationIdInvitations201;
  status: 201;
};

export type postOrganizationByOrganizationIdInvitationsResponse401 = {
  data: PostOrganizationByOrganizationIdInvitations401;
  status: 401;
};

export type postOrganizationByOrganizationIdInvitationsResponse404 = {
  data: PostOrganizationByOrganizationIdInvitations404;
  status: 404;
};

export type postOrganizationByOrganizationIdInvitationsResponse409 = {
  data: PostOrganizationByOrganizationIdInvitations409;
  status: 409;
};

export type postOrganizationByOrganizationIdInvitationsResponse422 = {
  data: PostOrganizationByOrganizationIdInvitations422;
  status: 422;
};

export type postOrganizationByOrganizationIdInvitationsResponseSuccess =
  postOrganizationByOrganizationIdInvitationsResponse201 & {
    headers: Headers;
  };
export type postOrganizationByOrganizationIdInvitationsResponseError = (
  | postOrganizationByOrganizationIdInvitationsResponse401
  | postOrganizationByOrganizationIdInvitationsResponse404
  | postOrganizationByOrganizationIdInvitationsResponse409
  | postOrganizationByOrganizationIdInvitationsResponse422
) & {
  headers: Headers;
};

export type postOrganizationByOrganizationIdInvitationsResponse =
  | postOrganizationByOrganizationIdInvitationsResponseSuccess
  | postOrganizationByOrganizationIdInvitationsResponseError;

export const getPostOrganizationByOrganizationIdInvitationsUrl = (
  organizationId: string,
) => {
  return `http://localhost:4000/organization/${organizationId}/invitations`;
};

/**
 * @summary Create Invitation
 */
export const postOrganizationByOrganizationIdInvitations = async (
  organizationId: string,
  postOrganizationByOrganizationIdInvitationsBody: PostOrganizationByOrganizationIdInvitationsBody,
  options?: RequestInit,
): Promise<postOrganizationByOrganizationIdInvitationsResponse> => {
  const res = await fetch(
    getPostOrganizationByOrganizationIdInvitationsUrl(organizationId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(postOrganizationByOrganizationIdInvitationsBody),
    },
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postOrganizationByOrganizationIdInvitationsResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postOrganizationByOrganizationIdInvitationsResponse;
};

export type getOrganizationByOrganizationIdInvitationsResponse200 = {
  data: GetOrganizationByOrganizationIdInvitations200;
  status: 200;
};

export type getOrganizationByOrganizationIdInvitationsResponse401 = {
  data: GetOrganizationByOrganizationIdInvitations401;
  status: 401;
};

export type getOrganizationByOrganizationIdInvitationsResponseSuccess =
  getOrganizationByOrganizationIdInvitationsResponse200 & {
    headers: Headers;
  };
export type getOrganizationByOrganizationIdInvitationsResponseError =
  getOrganizationByOrganizationIdInvitationsResponse401 & {
    headers: Headers;
  };

export type getOrganizationByOrganizationIdInvitationsResponse =
  | getOrganizationByOrganizationIdInvitationsResponseSuccess
  | getOrganizationByOrganizationIdInvitationsResponseError;

export const getGetOrganizationByOrganizationIdInvitationsUrl = (
  organizationId: string,
) => {
  return `http://localhost:4000/organization/${organizationId}/invitations`;
};

/**
 * @summary Find Sent Invitations
 */
export const getOrganizationByOrganizationIdInvitations = async (
  organizationId: string,
  options?: RequestInit,
): Promise<getOrganizationByOrganizationIdInvitationsResponse> => {
  const res = await fetch(
    getGetOrganizationByOrganizationIdInvitationsUrl(organizationId),
    {
      ...options,
      method: 'GET',
    },
  );

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getOrganizationByOrganizationIdInvitationsResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getOrganizationByOrganizationIdInvitationsResponse;
};

export type patchOrganizationInvitationResponse200 = {
  data: PatchOrganizationInvitation200;
  status: 200;
};

export type patchOrganizationInvitationResponse401 = {
  data: PatchOrganizationInvitation401;
  status: 401;
};

export type patchOrganizationInvitationResponse403 = {
  data: PatchOrganizationInvitation403;
  status: 403;
};

export type patchOrganizationInvitationResponse404 = {
  data: PatchOrganizationInvitation404;
  status: 404;
};

export type patchOrganizationInvitationResponse422 = {
  data: PatchOrganizationInvitation422;
  status: 422;
};

export type patchOrganizationInvitationResponseSuccess =
  patchOrganizationInvitationResponse200 & {
    headers: Headers;
  };
export type patchOrganizationInvitationResponseError = (
  | patchOrganizationInvitationResponse401
  | patchOrganizationInvitationResponse403
  | patchOrganizationInvitationResponse404
  | patchOrganizationInvitationResponse422
) & {
  headers: Headers;
};

export type patchOrganizationInvitationResponse =
  | patchOrganizationInvitationResponseSuccess
  | patchOrganizationInvitationResponseError;

export const getPatchOrganizationInvitationUrl = () => {
  return `http://localhost:4000/organization/invitation`;
};

/**
 * @summary Change Organization Invitation Status
 */
export const patchOrganizationInvitation = async (
  patchOrganizationInvitationBody: PatchOrganizationInvitationBody,
  options?: RequestInit,
): Promise<patchOrganizationInvitationResponse> => {
  const res = await fetch(getPatchOrganizationInvitationUrl(), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchOrganizationInvitationBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchOrganizationInvitationResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as patchOrganizationInvitationResponse;
};

export type getOrganizationInvitationsResponse200 = {
  data: GetOrganizationInvitations200;
  status: 200;
};

export type getOrganizationInvitationsResponse401 = {
  data: GetOrganizationInvitations401;
  status: 401;
};

export type getOrganizationInvitationsResponseSuccess =
  getOrganizationInvitationsResponse200 & {
    headers: Headers;
  };
export type getOrganizationInvitationsResponseError =
  getOrganizationInvitationsResponse401 & {
    headers: Headers;
  };

export type getOrganizationInvitationsResponse =
  | getOrganizationInvitationsResponseSuccess
  | getOrganizationInvitationsResponseError;

export const getGetOrganizationInvitationsUrl = () => {
  return `http://localhost:4000/organization/invitations`;
};

/**
 * @summary Find Received Invitations
 */
export const getOrganizationInvitations = async (
  options?: RequestInit,
): Promise<getOrganizationInvitationsResponse> => {
  const res = await fetch(getGetOrganizationInvitationsUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getOrganizationInvitationsResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getOrganizationInvitationsResponse;
};

export type getUserMeResponse200 = {
  data: GetUserMe200;
  status: 200;
};

export type getUserMeResponse401 = {
  data: GetUserMe401;
  status: 401;
};

export type getUserMeResponse404 = {
  data: GetUserMe404;
  status: 404;
};

export type getUserMeResponseSuccess = getUserMeResponse200 & {
  headers: Headers;
};
export type getUserMeResponseError = (
  | getUserMeResponse401
  | getUserMeResponse404
) & {
  headers: Headers;
};

export type getUserMeResponse =
  | getUserMeResponseSuccess
  | getUserMeResponseError;

export const getGetUserMeUrl = () => {
  return `http://localhost:4000/user/me`;
};

/**
 * Retrieves the profile information of the currently authenticated user.
 * @summary Get Current User
 */
export const getUserMe = async (
  options?: RequestInit,
): Promise<getUserMeResponse> => {
  const res = await fetch(getGetUserMeUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUserMeResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getUserMeResponse;
};

export type getUserResponse200 = {
  data: GetUser200;
  status: 200;
};

export type getUserResponse401 = {
  data: GetUser401;
  status: 401;
};

export type getUserResponse404 = {
  data: GetUser404;
  status: 404;
};

export type getUserResponse422 = {
  data: GetUser422;
  status: 422;
};

export type getUserResponseSuccess = getUserResponse200 & {
  headers: Headers;
};
export type getUserResponseError = (
  | getUserResponse401
  | getUserResponse404
  | getUserResponse422
) & {
  headers: Headers;
};

export type getUserResponse = getUserResponseSuccess | getUserResponseError;

export const getGetUserUrl = (params: GetUserParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `http://localhost:4000/user/?${stringifiedParams}`
    : `http://localhost:4000/user/`;
};

/**
 * Retrieves user information
 * @summary Get User
 */
export const getUser = async (
  params: GetUserParams,
  options?: RequestInit,
): Promise<getUserResponse> => {
  const res = await fetch(getGetUserUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUserResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getUserResponse;
};
