/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
export type PostAuthSignInBody = {
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  password: string;
};

export type PostAuthSignIn200DataUser = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$ */
  id: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  name: string;
};

export type PostAuthSignIn200Data = {
  accessToken: string;
  refreshToken: string;
  user: PostAuthSignIn200DataUser;
};

export type PostAuthSignIn200Meta = {
  unixTimestamp: number;
  requestId?: string;
};

export type PostAuthSignIn200 = {
  success: true;
  data: PostAuthSignIn200Data;
  error: unknown | null;
  meta: PostAuthSignIn200Meta;
};

export type PostAuthSignIn400Error = {
  code: string;
  details?: unknown;
};

export type PostAuthSignIn400Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Invalid input or missing required fields
 */
export type PostAuthSignIn400 = {
  success: false;
  data: unknown | null;
  error: PostAuthSignIn400Error;
  meta: PostAuthSignIn400Meta;
};

export type PostAuthSignIn401Error = {
  code: string;
  details?: unknown;
};

export type PostAuthSignIn401Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Invalid username or password
 */
export type PostAuthSignIn401 = {
  success: false;
  data: unknown | null;
  error: PostAuthSignIn401Error;
  meta: PostAuthSignIn401Meta;
};

export type PostAuthSignUpBody = {
  /**
   * @minLength 2
   * @maxLength 20
   */
  name: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  password: string;
};

export type PostAuthSignUp201Data = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$ */
  id: string;
};

export type PostAuthSignUp201Meta = {
  unixTimestamp: number;
  requestId?: string;
};

export type PostAuthSignUp201 = {
  success: true;
  data: PostAuthSignUp201Data;
  error: unknown | null;
  meta: PostAuthSignUp201Meta;
};

export type PostAuthSignUp400Error = {
  code: string;
  details?: unknown;
};

export type PostAuthSignUp400Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Invalid input or missing required fields
 */
export type PostAuthSignUp400 = {
  success: false;
  data: unknown | null;
  error: PostAuthSignUp400Error;
  meta: PostAuthSignUp400Meta;
};

export type PostAuthSignUp409Error = {
  code: string;
  details?: unknown;
};

export type PostAuthSignUp409Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * User already exists
 */
export type PostAuthSignUp409 = {
  success: false;
  data: unknown | null;
  error: PostAuthSignUp409Error;
  meta: PostAuthSignUp409Meta;
};

export type PostAuthSignOutBody = { [key: string]: unknown };

export type PostAuthSignOut200Data = { [key: string]: unknown };

export type PostAuthSignOut200Meta = {
  unixTimestamp: number;
  requestId?: string;
};

export type PostAuthSignOut200 = {
  success: true;
  data: PostAuthSignOut200Data;
  error: unknown | null;
  meta: PostAuthSignOut200Meta;
};

export type PostAuthSignOut401Error = {
  code: string;
  details?: unknown;
};

export type PostAuthSignOut401Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Invalid refreshToken
 */
export type PostAuthSignOut401 = {
  success: false;
  data: unknown | null;
  error: PostAuthSignOut401Error;
  meta: PostAuthSignOut401Meta;
};

export type PostAuthRefreshBody = { [key: string]: unknown };

export type PostAuthRefresh200DataUser = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$ */
  id: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  name: string;
};

export type PostAuthRefresh200Data = {
  accessToken: string;
  refreshToken: string;
  user: PostAuthRefresh200DataUser;
};

export type PostAuthRefresh200Meta = {
  unixTimestamp: number;
  requestId?: string;
};

export type PostAuthRefresh200 = {
  success: true;
  data: PostAuthRefresh200Data;
  error: unknown | null;
  meta: PostAuthRefresh200Meta;
};

export type PostAuthRefresh401Error = {
  code: string;
  details?: unknown;
};

export type PostAuthRefresh401Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Invalid refreshToken
 */
export type PostAuthRefresh401 = {
  success: false;
  data: unknown | null;
  error: PostAuthRefresh401Error;
  meta: PostAuthRefresh401Meta;
};

export type PostAuthRefresh404Error = {
  code: string;
  details?: unknown;
};

export type PostAuthRefresh404Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Session Not Found
 */
export type PostAuthRefresh404 = {
  success: false;
  data: unknown | null;
  error: PostAuthRefresh404Error;
  meta: PostAuthRefresh404Meta;
};

export type PostOrganizationBody = {
  /**
   * @minLength 1
   * @maxLength 20
   */
  title: string;
};

export type PostOrganization201Data = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$ */
  id: string;
  title: string;
};

export type PostOrganization201Meta = {
  unixTimestamp: number;
  requestId?: string;
};

export type PostOrganization201 = {
  success: true;
  data: PostOrganization201Data;
  error: unknown | null;
  meta: PostOrganization201Meta;
};

export type PostOrganization401Error = {
  code: string;
  details?: unknown;
};

export type PostOrganization401Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Access token verification failed.
 */
export type PostOrganization401 = {
  success: false;
  data: unknown | null;
  error: PostOrganization401Error;
  meta: PostOrganization401Meta;
};

export type PostOrganization404Error = {
  code: string;
  details?: unknown;
};

export type PostOrganization404Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Invalid data or missing required fields
 */
export type PostOrganization404 = {
  success: false;
  data: unknown | null;
  error: PostOrganization404Error;
  meta: PostOrganization404Meta;
};

export type PostOrganization409Error = {
  code: string;
  details?: unknown;
};

export type PostOrganization409Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Organization name already exists
 */
export type PostOrganization409 = {
  success: false;
  data: unknown | null;
  error: PostOrganization409Error;
  meta: PostOrganization409Meta;
};

export type PostOrganizationAddMembersBodyMembersItemRole =
  (typeof PostOrganizationAddMembersBodyMembersItemRole)[keyof typeof PostOrganizationAddMembersBodyMembersItemRole];

export const PostOrganizationAddMembersBodyMembersItemRole = {
  ADMIN: 'ADMIN',
  MAINTAINER: 'MAINTAINER',
  MEMBER: 'MEMBER',
} as const;

export type PostOrganizationAddMembersBodyMembersItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$ */
  userId: string;
  role: PostOrganizationAddMembersBodyMembersItemRole;
};

export type PostOrganizationAddMembersBody = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$ */
  organizationId: string;
  members: PostOrganizationAddMembersBodyMembersItem[];
};

export type PostOrganizationAddMembers201Data = {
  message: string;
};

export type PostOrganizationAddMembers201Meta = {
  unixTimestamp: number;
  requestId?: string;
};

export type PostOrganizationAddMembers201 = {
  success: true;
  data: PostOrganizationAddMembers201Data;
  error: unknown | null;
  meta: PostOrganizationAddMembers201Meta;
};

export type PostOrganizationAddMembers400Error = {
  code: string;
  details?: unknown;
};

export type PostOrganizationAddMembers400Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Invalid data or missing required fields
 */
export type PostOrganizationAddMembers400 = {
  success: false;
  data: unknown | null;
  error: PostOrganizationAddMembers400Error;
  meta: PostOrganizationAddMembers400Meta;
};

export type PostOrganizationAddMembers401Error = {
  code: string;
  details?: unknown;
};

export type PostOrganizationAddMembers401Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Access token verification failed.
 */
export type PostOrganizationAddMembers401 = {
  success: false;
  data: unknown | null;
  error: PostOrganizationAddMembers401Error;
  meta: PostOrganizationAddMembers401Meta;
};

export type PostOrganizationAddMembers403Error = {
  code: string;
  details?: unknown;
};

export type PostOrganizationAddMembers403Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Member cannot be added to this organization
 */
export type PostOrganizationAddMembers403 = {
  success: false;
  data: unknown | null;
  error: PostOrganizationAddMembers403Error;
  meta: PostOrganizationAddMembers403Meta;
};

export type PostOrganizationAddMembers404Error = {
  code: string;
  details?: unknown;
};

export type PostOrganizationAddMembers404Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Organization not found
 */
export type PostOrganizationAddMembers404 = {
  success: false;
  data: unknown | null;
  error: PostOrganizationAddMembers404Error;
  meta: PostOrganizationAddMembers404Meta;
};

export type PostOrganizationAddMembers409Error = {
  code: string;
  details?: unknown;
};

export type PostOrganizationAddMembers409Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Member already exists in the organization
 */
export type PostOrganizationAddMembers409 = {
  success: false;
  data: unknown | null;
  error: PostOrganizationAddMembers409Error;
  meta: PostOrganizationAddMembers409Meta;
};

export type GetUserMe200Data = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$ */
  id: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  name: string;
};

export type GetUserMe200Meta = {
  unixTimestamp: number;
  requestId?: string;
};

export type GetUserMe200 = {
  success: true;
  data: GetUserMe200Data;
  error: unknown | null;
  meta: GetUserMe200Meta;
};

export type GetUserMe401Error = {
  code: string;
  details?: unknown;
};

export type GetUserMe401Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * Access token verification failed.
 */
export type GetUserMe401 = {
  success: false;
  data: unknown | null;
  error: GetUserMe401Error;
  meta: GetUserMe401Meta;
};

export type GetUserMe404Error = {
  code: string;
  details?: unknown;
};

export type GetUserMe404Meta = {
  unixTimestamp: number;
  requestId?: string;
};

/**
 * User not found
 */
export type GetUserMe404 = {
  success: false;
  data: unknown | null;
  error: GetUserMe404Error;
  meta: GetUserMe404Meta;
};

export type postAuthSignInResponse200 = {
  data: PostAuthSignIn200;
  status: 200;
};

export type postAuthSignInResponse400 = {
  data: PostAuthSignIn400;
  status: 400;
};

export type postAuthSignInResponse401 = {
  data: PostAuthSignIn401;
  status: 401;
};

export type postAuthSignInResponseSuccess = postAuthSignInResponse200 & {
  headers: Headers;
};
export type postAuthSignInResponseError = (
  | postAuthSignInResponse400
  | postAuthSignInResponse401
) & {
  headers: Headers;
};

export type postAuthSignInResponse =
  | postAuthSignInResponseSuccess
  | postAuthSignInResponseError;

export const getPostAuthSignInUrl = () => {
  return `http://localhost:4000/auth/sign-in`;
};

/**
 * @summary Sign In User
 */
export const postAuthSignIn = async (
  postAuthSignInBody: PostAuthSignInBody,
  options?: RequestInit,
): Promise<postAuthSignInResponse> => {
  const res = await fetch(getPostAuthSignInUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postAuthSignInBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postAuthSignInResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postAuthSignInResponse;
};

export type postAuthSignUpResponse201 = {
  data: PostAuthSignUp201;
  status: 201;
};

export type postAuthSignUpResponse400 = {
  data: PostAuthSignUp400;
  status: 400;
};

export type postAuthSignUpResponse409 = {
  data: PostAuthSignUp409;
  status: 409;
};

export type postAuthSignUpResponseSuccess = postAuthSignUpResponse201 & {
  headers: Headers;
};
export type postAuthSignUpResponseError = (
  | postAuthSignUpResponse400
  | postAuthSignUpResponse409
) & {
  headers: Headers;
};

export type postAuthSignUpResponse =
  | postAuthSignUpResponseSuccess
  | postAuthSignUpResponseError;

export const getPostAuthSignUpUrl = () => {
  return `http://localhost:4000/auth/sign-up`;
};

/**
 * @summary Sign Up User
 */
export const postAuthSignUp = async (
  postAuthSignUpBody: PostAuthSignUpBody,
  options?: RequestInit,
): Promise<postAuthSignUpResponse> => {
  const res = await fetch(getPostAuthSignUpUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postAuthSignUpBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postAuthSignUpResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postAuthSignUpResponse;
};

export type postAuthSignOutResponse200 = {
  data: PostAuthSignOut200;
  status: 200;
};

export type postAuthSignOutResponse401 = {
  data: PostAuthSignOut401;
  status: 401;
};

export type postAuthSignOutResponseSuccess = postAuthSignOutResponse200 & {
  headers: Headers;
};
export type postAuthSignOutResponseError = postAuthSignOutResponse401 & {
  headers: Headers;
};

export type postAuthSignOutResponse =
  | postAuthSignOutResponseSuccess
  | postAuthSignOutResponseError;

export const getPostAuthSignOutUrl = () => {
  return `http://localhost:4000/auth/sign-out`;
};

/**
 * @summary Sign Out
 */
export const postAuthSignOut = async (
  postAuthSignOutBody: PostAuthSignOutBody,
  options?: RequestInit,
): Promise<postAuthSignOutResponse> => {
  const res = await fetch(getPostAuthSignOutUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postAuthSignOutBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postAuthSignOutResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postAuthSignOutResponse;
};

export type postAuthRefreshResponse200 = {
  data: PostAuthRefresh200;
  status: 200;
};

export type postAuthRefreshResponse401 = {
  data: PostAuthRefresh401;
  status: 401;
};

export type postAuthRefreshResponse404 = {
  data: PostAuthRefresh404;
  status: 404;
};

export type postAuthRefreshResponseSuccess = postAuthRefreshResponse200 & {
  headers: Headers;
};
export type postAuthRefreshResponseError = (
  | postAuthRefreshResponse401
  | postAuthRefreshResponse404
) & {
  headers: Headers;
};

export type postAuthRefreshResponse =
  | postAuthRefreshResponseSuccess
  | postAuthRefreshResponseError;

export const getPostAuthRefreshUrl = () => {
  return `http://localhost:4000/auth/refresh`;
};

/**
 * @summary Refresh Auth Token
 */
export const postAuthRefresh = async (
  postAuthRefreshBody: PostAuthRefreshBody,
  options?: RequestInit,
): Promise<postAuthRefreshResponse> => {
  const res = await fetch(getPostAuthRefreshUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postAuthRefreshBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postAuthRefreshResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postAuthRefreshResponse;
};

export type postOrganizationResponse201 = {
  data: PostOrganization201;
  status: 201;
};

export type postOrganizationResponse401 = {
  data: PostOrganization401;
  status: 401;
};

export type postOrganizationResponse404 = {
  data: PostOrganization404;
  status: 404;
};

export type postOrganizationResponse409 = {
  data: PostOrganization409;
  status: 409;
};

export type postOrganizationResponseSuccess = postOrganizationResponse201 & {
  headers: Headers;
};
export type postOrganizationResponseError = (
  | postOrganizationResponse401
  | postOrganizationResponse404
  | postOrganizationResponse409
) & {
  headers: Headers;
};

export type postOrganizationResponse =
  | postOrganizationResponseSuccess
  | postOrganizationResponseError;

export const getPostOrganizationUrl = () => {
  return `http://localhost:4000/organization/`;
};

/**
 * @summary Create Organization
 */
export const postOrganization = async (
  postOrganizationBody: PostOrganizationBody,
  options?: RequestInit,
): Promise<postOrganizationResponse> => {
  const res = await fetch(getPostOrganizationUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postOrganizationBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postOrganizationResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postOrganizationResponse;
};

export type postOrganizationAddMembersResponse201 = {
  data: PostOrganizationAddMembers201;
  status: 201;
};

export type postOrganizationAddMembersResponse400 = {
  data: PostOrganizationAddMembers400;
  status: 400;
};

export type postOrganizationAddMembersResponse401 = {
  data: PostOrganizationAddMembers401;
  status: 401;
};

export type postOrganizationAddMembersResponse403 = {
  data: PostOrganizationAddMembers403;
  status: 403;
};

export type postOrganizationAddMembersResponse404 = {
  data: PostOrganizationAddMembers404;
  status: 404;
};

export type postOrganizationAddMembersResponse409 = {
  data: PostOrganizationAddMembers409;
  status: 409;
};

export type postOrganizationAddMembersResponseSuccess =
  postOrganizationAddMembersResponse201 & {
    headers: Headers;
  };
export type postOrganizationAddMembersResponseError = (
  | postOrganizationAddMembersResponse400
  | postOrganizationAddMembersResponse401
  | postOrganizationAddMembersResponse403
  | postOrganizationAddMembersResponse404
  | postOrganizationAddMembersResponse409
) & {
  headers: Headers;
};

export type postOrganizationAddMembersResponse =
  | postOrganizationAddMembersResponseSuccess
  | postOrganizationAddMembersResponseError;

export const getPostOrganizationAddMembersUrl = () => {
  return `http://localhost:4000/organization/add-members`;
};

/**
 * @summary Add Members
 */
export const postOrganizationAddMembers = async (
  postOrganizationAddMembersBody: PostOrganizationAddMembersBody,
  options?: RequestInit,
): Promise<postOrganizationAddMembersResponse> => {
  const res = await fetch(getPostOrganizationAddMembersUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postOrganizationAddMembersBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postOrganizationAddMembersResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postOrganizationAddMembersResponse;
};

export type getUserMeResponse200 = {
  data: GetUserMe200;
  status: 200;
};

export type getUserMeResponse401 = {
  data: GetUserMe401;
  status: 401;
};

export type getUserMeResponse404 = {
  data: GetUserMe404;
  status: 404;
};

export type getUserMeResponseSuccess = getUserMeResponse200 & {
  headers: Headers;
};
export type getUserMeResponseError = (
  | getUserMeResponse401
  | getUserMeResponse404
) & {
  headers: Headers;
};

export type getUserMeResponse =
  | getUserMeResponseSuccess
  | getUserMeResponseError;

export const getGetUserMeUrl = () => {
  return `http://localhost:4000/user/me`;
};

/**
 * Retrieves the profile information of the currently authenticated user.
 * @summary Get Current User
 */
export const getUserMe = async (
  options?: RequestInit,
): Promise<getUserMeResponse> => {
  const res = await fetch(getGetUserMeUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUserMeResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getUserMeResponse;
};
