/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import * as zod from 'zod';

/**
 * @summary Sign Up User
 */
export const postAuthSignUpBodyEmailRegExp = new RegExp(
  "^(?!\\.)(?!.\*\\.\\.)([A-Za-z0-9_'+\\-\\.]\*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]\*\\.)+[A-Za-z]{2,}$",
);
export const postAuthSignUpBodyNameMin = 5;
export const postAuthSignUpBodyNameMax = 20;

export const PostAuthSignUpBody = zod.object({
  email: zod.email().regex(postAuthSignUpBodyEmailRegExp),
  name: zod
    .string()
    .min(postAuthSignUpBodyNameMin)
    .max(postAuthSignUpBodyNameMax),
  password: zod.string(),
});

/**
 * @summary Sign In User
 */
export const postAuthSignInBodyEmailRegExp = new RegExp(
  "^(?!\\.)(?!.\*\\.\\.)([A-Za-z0-9_'+\\-\\.]\*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]\*\\.)+[A-Za-z]{2,}$",
);

export const PostAuthSignInBody = zod.object({
  email: zod.email().regex(postAuthSignInBodyEmailRegExp),
  password: zod.string(),
});

export const postAuthSignInResponseDataUserIdRegExp = new RegExp(
  '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$',
);
export const postAuthSignInResponseDataUserEmailRegExp = new RegExp(
  "^(?!\\.)(?!.\*\\.\\.)([A-Za-z0-9_'+\\-\\.]\*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]\*\\.)+[A-Za-z]{2,}$",
);

export const PostAuthSignInResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    accessToken: zod.string(),
    user: zod.object({
      id: zod.uuid().regex(postAuthSignInResponseDataUserIdRegExp),
      email: zod.email().regex(postAuthSignInResponseDataUserEmailRegExp),
      name: zod.string(),
    }),
  }),
  error: zod.unknown().nullable(),
  meta: zod.object({
    unixTimestamp: zod.number(),
    requestId: zod.string().optional(),
  }),
});

/**
 * Retrieves the profile information of the currently authenticated user.
 * @summary Get Current User
 */
export const getAuthMeResponseDataIdRegExp = new RegExp(
  '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$',
);
export const getAuthMeResponseDataEmailRegExp = new RegExp(
  "^(?!\\.)(?!.\*\\.\\.)([A-Za-z0-9_'+\\-\\.]\*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]\*\\.)+[A-Za-z]{2,}$",
);

export const GetAuthMeResponse = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.uuid().regex(getAuthMeResponseDataIdRegExp),
    email: zod.email().regex(getAuthMeResponseDataEmailRegExp),
    name: zod.string(),
  }),
  error: zod.unknown().nullable(),
  meta: zod.object({
    unixTimestamp: zod.number(),
    requestId: zod.string().optional(),
  }),
});

/**
 * @summary Create Organization
 */
export const PostOrganizationBody = zod.object({
  title: zod.string(),
});

/**
 * @summary Add Members
 */
export const postOrganizationAddMembersBodyOrganizationIdRegExp = new RegExp(
  '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$',
);
export const postOrganizationAddMembersBodyMembersItemUserIdRegExp = new RegExp(
  '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$',
);

export const PostOrganizationAddMembersBody = zod.object({
  organizationId: zod
    .uuid()
    .regex(postOrganizationAddMembersBodyOrganizationIdRegExp),
  members: zod.array(
    zod.object({
      userId: zod
        .uuid()
        .regex(postOrganizationAddMembersBodyMembersItemUserIdRegExp),
      role: zod.enum(['ADMIN', 'MAINTAINER', 'MEMBER']),
    }),
  ),
});
