/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import * as zod from 'zod';

import { zodParams } from '../lib/zod-params';

/**
 * @summary Create Organization
 */
export const PostOrganizationBody = zod.object({
  title: zod.string(
    zodParams({
      operationId: 'postOrganization',
      location: 'body',
      schemaName: 'PostOrganizationBody',
      fieldPath: ['title'],
      validator: 'string',
    }),
  ),
});

export const PostOrganizationResponse = zod.object({
  success: zod.literal(
    true,
    zodParams({
      operationId: 'postOrganization',
      location: 'response',
      schemaName: 'PostOrganizationResponse',
      fieldPath: ['success'],
      validator: 'literal',
    }),
  ),
  data: zod.object({
    message: zod.string(
      zodParams({
        operationId: 'postOrganization',
        location: 'response',
        schemaName: 'PostOrganizationResponse',
        fieldPath: ['data', 'message'],
        validator: 'string',
      }),
    ),
  }),
  error: zod.unknown().nullable(),
  meta: zod.object({
    unixTimestamp: zod.number(
      zodParams({
        operationId: 'postOrganization',
        location: 'response',
        schemaName: 'PostOrganizationResponse',
        fieldPath: ['meta', 'unixTimestamp'],
        validator: 'number',
      }),
    ),
    requestId: zod
      .string(
        zodParams({
          operationId: 'postOrganization',
          location: 'response',
          schemaName: 'PostOrganizationResponse',
          fieldPath: ['meta', 'requestId'],
          validator: 'string',
        }),
      )
      .optional(),
  }),
});

/**
 * @summary Add Members
 */
export const postOrganizationAddMembersBodyOrganizationIdRegExp = new RegExp(
  '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$',
);
export const postOrganizationAddMembersBodyMembersItemUserIdRegExp = new RegExp(
  '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$',
);

export const PostOrganizationAddMembersBody = zod.object({
  organizationId: zod
    .uuid(
      zodParams({
        operationId: 'postOrganizationAdd-members',
        location: 'body',
        schemaName: 'PostOrganizationAddMembersBody',
        fieldPath: ['organizationId'],
        validator: 'uuid',
      }),
    )
    .regex(
      postOrganizationAddMembersBodyOrganizationIdRegExp,
      zodParams({
        operationId: 'postOrganizationAdd-members',
        location: 'body',
        schemaName: 'PostOrganizationAddMembersBody',
        fieldPath: ['organizationId'],
        validator: 'regex',
      }),
    ),
  members: zod.array(
    zod.object({
      userId: zod
        .uuid(
          zodParams({
            operationId: 'postOrganizationAdd-members',
            location: 'body',
            schemaName: 'PostOrganizationAddMembersBody',
            fieldPath: ['members', 'userId'],
            validator: 'uuid',
          }),
        )
        .regex(
          postOrganizationAddMembersBodyMembersItemUserIdRegExp,
          zodParams({
            operationId: 'postOrganizationAdd-members',
            location: 'body',
            schemaName: 'PostOrganizationAddMembersBody',
            fieldPath: ['members', 'userId'],
            validator: 'regex',
          }),
        ),
      role: zod.enum(
        ['ADMIN', 'MAINTAINER', 'MEMBER'],
        zodParams({
          operationId: 'postOrganizationAdd-members',
          location: 'body',
          schemaName: 'PostOrganizationAddMembersBody',
          fieldPath: ['members', 'role'],
          validator: 'enum',
        }),
      ),
    }),
  ),
});

export const PostOrganizationAddMembersResponse = zod.object({
  success: zod.literal(
    true,
    zodParams({
      operationId: 'postOrganizationAdd-members',
      location: 'response',
      schemaName: 'PostOrganizationAddMembersResponse',
      fieldPath: ['success'],
      validator: 'literal',
    }),
  ),
  data: zod.object({
    message: zod.string(
      zodParams({
        operationId: 'postOrganizationAdd-members',
        location: 'response',
        schemaName: 'PostOrganizationAddMembersResponse',
        fieldPath: ['data', 'message'],
        validator: 'string',
      }),
    ),
  }),
  error: zod.unknown().nullable(),
  meta: zod.object({
    unixTimestamp: zod.number(
      zodParams({
        operationId: 'postOrganizationAdd-members',
        location: 'response',
        schemaName: 'PostOrganizationAddMembersResponse',
        fieldPath: ['meta', 'unixTimestamp'],
        validator: 'number',
      }),
    ),
    requestId: zod
      .string(
        zodParams({
          operationId: 'postOrganizationAdd-members',
          location: 'response',
          schemaName: 'PostOrganizationAddMembersResponse',
          fieldPath: ['meta', 'requestId'],
          validator: 'string',
        }),
      )
      .optional(),
  }),
});
