/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import * as zod from 'zod';

import { zodParams } from '../lib/zod-params';

/**
 * @summary Create Organization
 */
export const postOrganizationBodyTitleMax = 20;

export const PostOrganizationBody = zod.object({
  title: zod
    .string(
      zodParams({
        operationId: 'postOrganization',
        location: 'body',
        schemaName: 'PostOrganizationBody',
        fieldPath: ['title'],
        validator: 'string',
      }),
    )
    .min(
      1,
      zodParams({
        operationId: 'postOrganization',
        location: 'body',
        schemaName: 'PostOrganizationBody',
        fieldPath: ['title'],
        validator: 'min',
      }),
    )
    .max(
      postOrganizationBodyTitleMax,
      zodParams({
        operationId: 'postOrganization',
        location: 'body',
        schemaName: 'PostOrganizationBody',
        fieldPath: ['title'],
        validator: 'max',
      }),
    ),
});

export const postOrganizationResponseDataIdRegExp = new RegExp(
  '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$',
);

export const PostOrganizationResponse = zod.object({
  success: zod.literal(
    true,
    zodParams({
      operationId: 'postOrganization',
      location: 'response',
      schemaName: 'PostOrganizationResponse',
      fieldPath: ['success'],
      validator: 'literal',
    }),
  ),
  data: zod.object({
    id: zod
      .uuid(
        zodParams({
          operationId: 'postOrganization',
          location: 'response',
          schemaName: 'PostOrganizationResponse',
          fieldPath: ['data', 'id'],
          validator: 'uuid',
        }),
      )
      .regex(
        postOrganizationResponseDataIdRegExp,
        zodParams({
          operationId: 'postOrganization',
          location: 'response',
          schemaName: 'PostOrganizationResponse',
          fieldPath: ['data', 'id'],
          validator: 'regex',
        }),
      ),
    title: zod.string(
      zodParams({
        operationId: 'postOrganization',
        location: 'response',
        schemaName: 'PostOrganizationResponse',
        fieldPath: ['data', 'title'],
        validator: 'string',
      }),
    ),
  }),
  error: zod.unknown().nullable(),
  meta: zod.object({
    unixTimestamp: zod.number(
      zodParams({
        operationId: 'postOrganization',
        location: 'response',
        schemaName: 'PostOrganizationResponse',
        fieldPath: ['meta', 'unixTimestamp'],
        validator: 'number',
      }),
    ),
    requestId: zod
      .string(
        zodParams({
          operationId: 'postOrganization',
          location: 'response',
          schemaName: 'PostOrganizationResponse',
          fieldPath: ['meta', 'requestId'],
          validator: 'string',
        }),
      )
      .optional(),
  }),
});

/**
 * @summary Create Invitation
 */
export const PostOrganizationByOrganizationIdInvitationsParams = zod.object({
  organizationId: zod.string(
    zodParams({
      operationId: 'postOrganizationByOrganizationIdInvitations',
      location: 'param',
      schemaName: 'PostOrganizationByOrganizationIdInvitationsParams',
      fieldPath: ['organizationId'],
      validator: 'string',
    }),
  ),
});

export const postOrganizationByOrganizationIdInvitationsBodyEmailRegExp =
  new RegExp(
    "^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$",
  );

export const PostOrganizationByOrganizationIdInvitationsBody = zod.object({
  email: zod
    .string(
      zodParams({
        operationId: 'postOrganizationByOrganizationIdInvitations',
        location: 'body',
        schemaName: 'PostOrganizationByOrganizationIdInvitationsBody',
        fieldPath: ['email'],
        validator: 'string',
      }),
    )
    .regex(
      postOrganizationByOrganizationIdInvitationsBodyEmailRegExp,
      zodParams({
        operationId: 'postOrganizationByOrganizationIdInvitations',
        location: 'body',
        schemaName: 'PostOrganizationByOrganizationIdInvitationsBody',
        fieldPath: ['email'],
        validator: 'regex',
      }),
    ),
  role: zod.enum(
    ['ADMIN', 'MAINTAINER', 'MEMBER'],
    zodParams({
      operationId: 'postOrganizationByOrganizationIdInvitations',
      location: 'body',
      schemaName: 'PostOrganizationByOrganizationIdInvitationsBody',
      fieldPath: ['role'],
      validator: 'enum',
    }),
  ),
});

export const PostOrganizationByOrganizationIdInvitationsResponse = zod.object({
  success: zod.literal(
    true,
    zodParams({
      operationId: 'postOrganizationByOrganizationIdInvitations',
      location: 'response',
      schemaName: 'PostOrganizationByOrganizationIdInvitationsResponse',
      fieldPath: ['success'],
      validator: 'literal',
    }),
  ),
  data: zod.unknown().nullable(),
  error: zod.unknown().nullable(),
  meta: zod.object({
    unixTimestamp: zod.number(
      zodParams({
        operationId: 'postOrganizationByOrganizationIdInvitations',
        location: 'response',
        schemaName: 'PostOrganizationByOrganizationIdInvitationsResponse',
        fieldPath: ['meta', 'unixTimestamp'],
        validator: 'number',
      }),
    ),
    requestId: zod
      .string(
        zodParams({
          operationId: 'postOrganizationByOrganizationIdInvitations',
          location: 'response',
          schemaName: 'PostOrganizationByOrganizationIdInvitationsResponse',
          fieldPath: ['meta', 'requestId'],
          validator: 'string',
        }),
      )
      .optional(),
  }),
});
