// Generated by Orval post-processing.
// Do not edit manually.

export const authI18n = {
  'validation.PostAuthSignInBody.email.email': '',
  'validation.PostAuthSignInBody.email.regex': '',
  'validation.PostAuthSignInBody.password.string': '',
  'validation.PostAuthSignUpBody.email.email': '',
  'validation.PostAuthSignUpBody.email.regex': '',
  'validation.PostAuthSignUpBody.name.max': '',
  'validation.PostAuthSignUpBody.name.min': '',
  'validation.PostAuthSignUpBody.name.string': '',
  'validation.PostAuthSignUpBody.password.string': '',
} as const;

export type AuthI18nKey = keyof typeof authI18n;
