// Generated by Orval post-processing.
// Do not edit manually.

export const organizationI18n = {
  'validation.PostOrganizationAddMembersBody.members.role.enum': '',
  'validation.PostOrganizationAddMembersBody.members.userId.regex': '',
  'validation.PostOrganizationAddMembersBody.members.userId.uuid': '',
  'validation.PostOrganizationAddMembersBody.organizationId.regex': '',
  'validation.PostOrganizationAddMembersBody.organizationId.uuid': '',
  'validation.PostOrganizationBody.title.string': '',
} as const;

export type OrganizationI18nKey = keyof typeof organizationI18n;
