// src/lib/generate-validation-i18n.ts
import { access, mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { basename, dirname, extname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const CURRENT_DIR = dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = resolve(CURRENT_DIR, '../..');
const SCHEMA_DIR = resolve(ROOT_DIR, 'src/schema');
const OUTPUT_DIR = resolve(ROOT_DIR, 'src/i18n');
const INDEX_FILE = resolve(OUTPUT_DIR, 'index.ts');
const SCHEMA_INDEX_FILE = resolve(SCHEMA_DIR, 'index.ts');

const zodParamsPattern = /zodParams\(\{\s*([^}]*)\s*\}\)/g;

const propertyPattern = {
  location: /location:\s*['"]([^'"]+)['"]/,

  schemaName: /schemaName:\s*['"]([^'"]+)['"]/,

  fieldPath: /fieldPath:\s*\[([^\]]*)\]/,

  validator: /validator:\s*['"]([^'"]+)['"]/,
};

function parseFieldPath(rawFieldPath: string): string {
  return [...rawFieldPath.matchAll(/['"]([^'"]+)['"]/g)]
    .map((match) => match[1])
    .join('.');
}

function createValidationKey(input: {
  schemaName: string;
  fieldPath: string;
  validator: string;
}) {
  return [
    'validation',
    input.schemaName,
    input.fieldPath || 'root',
    input.validator,
  ].join('.');
}

function createExportName(tagName: string) {
  return `${tagName}I18n`;
}

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function createGeneratedFile(input: { tagName: string; keys: string[] }) {
  const exportName = createExportName(input.tagName);

  return `// Generated by Orval post-processing.
// Do not edit manually.

export const ${exportName} = {
${input.keys.map((key) => `  '${key}': '',`).join('\n')}
} as const

export type ${capitalize(input.tagName)}I18nKey =
  keyof typeof ${exportName}
`;
}

function createIndexFile(tagNames: string[]) {
  return `// Generated by Orval post-processing.
// Do not edit manually.

${tagNames
  .map((tagName) => {
    return `export * from './${tagName}'`;
  })
  .join('\n')}
`;
}

async function findSchemaFiles() {
  const entries = await readdir(SCHEMA_DIR, {
    withFileTypes: true,
  });

  return entries
    .filter((entry) => {
      return (
        entry.isFile() &&
        entry.name !== 'index.ts' &&
        !entry.name.startsWith('.') &&
        extname(entry.name) === '.ts'
      );
    })
    .map((entry) => {
      return resolve(SCHEMA_DIR, entry.name);
    })
    .sort();
}

function collectValidationKeys(schemaSource: string) {
  const keys = new Set<string>();

  for (const match of schemaSource.matchAll(zodParamsPattern)) {
    const block = match[1];

    const location = block.match(propertyPattern.location)?.[1];

    const schemaName = block.match(propertyPattern.schemaName)?.[1];

    const rawFieldPath = block.match(propertyPattern.fieldPath)?.[1];

    const validator = block.match(propertyPattern.validator)?.[1];

    if (
      location !== 'body' ||
      !schemaName ||
      rawFieldPath === undefined ||
      !validator
    ) {
      continue;
    }

    keys.add(
      createValidationKey({
        schemaName,
        fieldPath: parseFieldPath(rawFieldPath),
        validator,
      }),
    );
  }

  return [...keys].sort();
}

function createSchemaIndexFile(schemaNames: string[]) {
  return `${schemaNames
    .map((schemaName) => {
      return `export * from './${schemaName}'`;
    })
    .join('\n')}
`;
}

async function main() {
  await access(SCHEMA_DIR);

  const schemaFiles = await findSchemaFiles();

  const schemaNames = schemaFiles.map((schemaFile) =>
    basename(schemaFile, '.ts'),
  );

  await writeFile(
    SCHEMA_INDEX_FILE,
    createSchemaIndexFile(schemaNames),
    'utf8',
  );

  await mkdir(OUTPUT_DIR, {
    recursive: true,
  });

  const tagNames: string[] = [];

  for (const schemaFile of schemaFiles) {
    const tagName = basename(schemaFile, '.ts');

    const schemaSource = await readFile(schemaFile, 'utf8');

    const keys = collectValidationKeys(schemaSource);

    console.log(`[${tagName}] generated ${keys.length} keys`);

    tagNames.push(tagName);

    await writeFile(
      resolve(OUTPUT_DIR, `${tagName}.ts`),
      createGeneratedFile({
        tagName,
        keys,
      }),
      'utf8',
    );
  }

  await writeFile(INDEX_FILE, createIndexFile(tagNames), 'utf8');

  console.log('[validation-i18n] generated successfully');
}

main().catch((error) => {
  console.error('[validation-i18n] generation failed', error);

  process.exitCode = 1;
});
