// src/lib/generate-validation-i18n.ts
import { access, mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const CURRENT_DIR = dirname(fileURLToPath(import.meta.url));

const ROOT_DIR = resolve(CURRENT_DIR, '../..');

const SCHEMA_FILE = resolve(ROOT_DIR, 'src/schema/index.ts');

const OUTPUT_FILE = resolve(
  ROOT_DIR,
  'src/i18n/generated/validation.generated.ts',
);

const zodParamsPattern = /zodParams\(\{\s*([^}]*)\s*\}\)/g;

const propertyPattern = {
  location: /location:\s*['"]([^'"]+)['"]/,

  schemaName: /schemaName:\s*['"]([^'"]+)['"]/,

  fieldPath: /fieldPath:\s*\[([^\]]*)\]/,

  validator: /validator:\s*['"]([^'"]+)['"]/,
};

function parseFieldPath(rawFieldPath: string): string {
  return [...rawFieldPath.matchAll(/['"]([^'"]+)['"]/g)]
    .map((match) => match[1])
    .join('.');
}

function createValidationKey(input: {
  schemaName: string;
  fieldPath: string;
  validator: string;
}) {
  return [
    'validation',
    input.schemaName,
    input.fieldPath || 'root',
    input.validator,
  ].join('.');
}

function createGeneratedFile(keys: string[]) {
  return `// Generated by Orval post-processing.
// Do not edit manually.

export const validationMessages = {
${keys.map((key) => `  '${key}': '',`).join('\n')}
} as const

export type ValidationMessageKey =
  keyof typeof validationMessages
`;
}

async function main() {
  console.log('[schema file]', SCHEMA_FILE);
  console.log('[output file]', OUTPUT_FILE);

  const schemaSource = await readFile(SCHEMA_FILE, 'utf8');

  const keys = new Set<string>();

  for (const match of schemaSource.matchAll(zodParamsPattern)) {
    const block = match[1];

    const location = block.match(propertyPattern.location)?.[1];

    const schemaName = block.match(propertyPattern.schemaName)?.[1];

    const rawFieldPath = block.match(propertyPattern.fieldPath)?.[1];

    const validator = block.match(propertyPattern.validator)?.[1];

    if (
      location !== 'body' ||
      !schemaName ||
      rawFieldPath === undefined ||
      !validator
    ) {
      continue;
    }

    keys.add(
      createValidationKey({
        schemaName,
        fieldPath: parseFieldPath(rawFieldPath),
        validator,
      }),
    );
  }

  const sortedKeys = [...keys].sort();

  console.log('[key count]', sortedKeys.length);
  console.log('[keys]', sortedKeys);

  await mkdir(dirname(OUTPUT_FILE), {
    recursive: true,
  });

  await writeFile(OUTPUT_FILE, createGeneratedFile(sortedKeys), 'utf8');

  await access(OUTPUT_FILE);

  console.log('[validation-i18n] generated successfully');
}

main().catch((error) => {
  console.error('[validation-i18n] generation failed', error);

  process.exitCode = 1;
});
