import { access, mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { basename, dirname, extname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const CURRENT_DIR = dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = resolve(CURRENT_DIR, '../../../../');
const SCHEMA_DIR = resolve(ROOT_DIR, 'packages/api-client/src/schema');
const OUTPUT_DIR = resolve(ROOT_DIR, 'packages/i18n/src/validation');
const INDEX_FILE = resolve(OUTPUT_DIR, 'index.ts');

const zodParamsPattern = /zodParams\(\{\s*([^}]*)\s*\}\)/g;

const propertyPattern = {
  location: /location:\s*['"]([^'"]+)['"]/,

  schemaName: /schemaName:\s*['"]([^'"]+)['"]/,

  fieldPath: /fieldPath:\s*\[([^\]]*)\]/,

  validator: /validator:\s*['"]([^'"]+)['"]/,
};

function parseFieldPath(rawFieldPath: string): string {
  return [...rawFieldPath.matchAll(/['"]([^'"]+)['"]/g)]
    .map((match) => match[1])
    .join('.');
}

function createValidationKey(input: {
  schemaName: string;
  fieldPath: string;
  validator: string;
}) {
  return [
    'validation',
    input.schemaName,
    input.fieldPath || 'root',
    input.validator,
  ].join('.');
}

function createExportName(tagName: string) {
  return `I18N_${tagName.toUpperCase()}_VALIDATION`;
}

function createTypeName(tagName: string) {
  return `I18N_${tagName.toUpperCase()}_VALIDATION_KEY`;
}

function createGeneratedFile(input: { tagName: string; keys: string[] }) {
  const exportName = createExportName(input.tagName);

  return `// Generated by Orval Schemas.
export const ${exportName} = [
${input.keys.map((key) => `'${key}',`).join('\n')}
] as const

export type ${createTypeName(input.tagName)} =
  (typeof ${exportName})[number]
`;
}

async function findSchemaFiles() {
  const entries = await readdir(SCHEMA_DIR, {
    withFileTypes: true,
  });

  return entries
    .filter((entry) => {
      return (
        entry.isFile() &&
        entry.name !== 'index.ts' &&
        !entry.name.startsWith('.') &&
        extname(entry.name) === '.ts'
      );
    })
    .map((entry) => {
      return resolve(SCHEMA_DIR, entry.name);
    })
    .sort();
}

function collectValidationKeys(schemaSource: string) {
  const keys = new Set<string>();

  for (const match of schemaSource.matchAll(zodParamsPattern)) {
    const block = match[1];
    const location = block.match(propertyPattern.location)?.[1];
    const schemaName = block.match(propertyPattern.schemaName)?.[1];
    const rawFieldPath = block.match(propertyPattern.fieldPath)?.[1];
    const validator = block.match(propertyPattern.validator)?.[1];

    if (
      location !== 'body' ||
      !schemaName ||
      rawFieldPath === undefined ||
      !validator
    ) {
      continue;
    }

    keys.add(
      createValidationKey({
        schemaName,
        fieldPath: parseFieldPath(rawFieldPath),
        validator,
      }),
    );
  }

  return [...keys].sort();
}

function createIndexFile(tagNames: string[]) {
  return `
  ${tagNames
    .map((tagName) => {
      return `import type {${createTypeName(tagName)}} from './${tagName}.ts'`;
    })
    .join('\n')}

  export type I18N_VALIDATION_KEY = ${tagNames
    .map((tagName) => {
      return createTypeName(tagName);
    })
    .join('|')}
`;
}

async function main() {
  await access(SCHEMA_DIR);

  const schemaFiles = await findSchemaFiles();

  await mkdir(OUTPUT_DIR, {
    recursive: true,
  });

  const tagNames: string[] = [];

  for (const schemaFile of schemaFiles) {
    const tagName = basename(schemaFile, '.ts');

    const schemaSource = await readFile(schemaFile, 'utf8');

    const keys = collectValidationKeys(schemaSource);

    console.log(`[${tagName}] generated ${String(keys.length)} keys`);

    tagNames.push(tagName);

    await writeFile(
      resolve(OUTPUT_DIR, `${tagName}.ts`),
      createGeneratedFile({
        tagName,
        keys,
      }),
      'utf8',
    );
  }

  await writeFile(INDEX_FILE, createIndexFile(tagNames), 'utf8');

  console.log('[validation] generated successfully');
}

main().catch((error: unknown) => {
  console.error('[validation] generation failed', error);

  process.exitCode = 1;
});
