// Generated by Orval Schemas.
export const I18N_AUTH_VALIDATION = [
  'PostAuthSignInBody_email_regex',
  'PostAuthSignInBody_email_string',
  'PostAuthSignInBody_password_string',
  'PostAuthSignUpBody_email_regex',
  'PostAuthSignUpBody_email_string',
  'PostAuthSignUpBody_name_max',
  'PostAuthSignUpBody_name_min',
  'PostAuthSignUpBody_name_string',
  'PostAuthSignUpBody_password_string',
] as const;

export type I18N_AUTH_VALIDATION_KEY = (typeof I18N_AUTH_VALIDATION)[number];
