// Generated by Orval Schemas.
export const I18N_AUTH_VALIDATION = [
  'validation.PostAuthSignInBody.email.regex',
  'validation.PostAuthSignInBody.email.string',
  'validation.PostAuthSignInBody.password.string',
  'validation.PostAuthSignUpBody.email.regex',
  'validation.PostAuthSignUpBody.email.string',
  'validation.PostAuthSignUpBody.name.max',
  'validation.PostAuthSignUpBody.name.min',
  'validation.PostAuthSignUpBody.name.string',
  'validation.PostAuthSignUpBody.password.string',
] as const;

export type I18N_AUTH_VALIDATION_KEY = (typeof I18N_AUTH_VALIDATION)[number];
