// Generated by Orval Schemas.
export const I18N_ORGANIZATION_VALIDATION = [
  'PatchOrganizationInvitationBody_invitationId_regex',
  'PatchOrganizationInvitationBody_invitationId_uuid',
  'PatchOrganizationInvitationBody_status_enum',
  'PostOrganizationBody_title_max',
  'PostOrganizationBody_title_min',
  'PostOrganizationBody_title_string',
  'PostOrganizationByOrganizationIdInvitationsBody_email_regex',
  'PostOrganizationByOrganizationIdInvitationsBody_email_string',
  'PostOrganizationByOrganizationIdInvitationsBody_role_enum',
] as const;

export type I18N_ORGANIZATION_VALIDATION_KEY =
  (typeof I18N_ORGANIZATION_VALIDATION)[number];
