// Generated by Orval Schemas.
export const I18N_ORGANIZATION_VALIDATION = [
  'PostOrganizationAddMembersBody_members_role_enum',
  'PostOrganizationAddMembersBody_members_userId_regex',
  'PostOrganizationAddMembersBody_members_userId_uuid',
  'PostOrganizationAddMembersBody_organizationId_regex',
  'PostOrganizationAddMembersBody_organizationId_uuid',
  'PostOrganizationBody_title_max',
  'PostOrganizationBody_title_min',
  'PostOrganizationBody_title_string',
] as const;

export type I18N_ORGANIZATION_VALIDATION_KEY =
  (typeof I18N_ORGANIZATION_VALIDATION)[number];
