// Generated by Orval Schemas.
export const I18N_ORGANIZATION_VALIDATION = [
  'validation.PostOrganizationAddMembersBody.members.role.enum',
  'validation.PostOrganizationAddMembersBody.members.userId.regex',
  'validation.PostOrganizationAddMembersBody.members.userId.uuid',
  'validation.PostOrganizationAddMembersBody.organizationId.regex',
  'validation.PostOrganizationAddMembersBody.organizationId.uuid',
  'validation.PostOrganizationBody.title.string',
] as const;

export type I18N_ORGANIZATION_VALIDATION_KEY =
  (typeof I18N_ORGANIZATION_VALIDATION)[number];
