// Generated by Orval Schemas.
export const I18N_USER_VALIDATION = [
  'GetUserQueryParams_email_regex',
  'GetUserQueryParams_email_string',
] as const;

export type I18N_USER_VALIDATION_KEY = (typeof I18N_USER_VALIDATION)[number];
