/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import { z as zod } from 'zod';

export const getAuthMe200DataIdRegExp = new RegExp(
  '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$',
);
export const getAuthMe200DataEmailRegExp = new RegExp(
  "^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$",
);

export const GetAuthMe200 = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.uuid().regex(getAuthMe200DataIdRegExp),
    email: zod.string().regex(getAuthMe200DataEmailRegExp),
    name: zod.string(),
  }),
  error: zod.unknown().nullable(),
  meta: zod.object({
    unixTimestamp: zod.number(),
    requestId: zod.string().optional(),
  }),
});

export type GetAuthMe200 = zod.input<typeof GetAuthMe200>;
export type GetAuthMe200Output = zod.output<typeof GetAuthMe200>;
