/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import { z as zod } from 'zod';

export const GetAuthMe401 = zod
  .object({
    success: zod.literal(false),
    data: zod.unknown().nullable(),
    error: zod.object({
      code: zod.string(),
      details: zod.unknown().optional(),
    }),
    meta: zod.object({
      unixTimestamp: zod.number(),
      requestId: zod.string().optional(),
    }),
  })
  .describe('Access token verification failed.');

export type GetAuthMe401 = zod.input<typeof GetAuthMe401>;
export type GetAuthMe401Output = zod.output<typeof GetAuthMe401>;
