/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import { z as zod } from 'zod';

export const postOrganizationAddMembersBodyOrganizationIdRegExp = new RegExp(
  '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$',
);
export const postOrganizationAddMembersBodyMembersItemUserIdRegExp = new RegExp(
  '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$',
);

export const PostOrganizationAddMembersBody = zod.object({
  organizationId: zod
    .uuid()
    .regex(postOrganizationAddMembersBodyOrganizationIdRegExp),
  members: zod.array(
    zod.object({
      userId: zod
        .uuid()
        .regex(postOrganizationAddMembersBodyMembersItemUserIdRegExp),
      role: zod.enum(['ADMIN', 'MAINTAINER', 'MEMBER']),
    }),
  ),
});

export type PostOrganizationAddMembersBody = zod.input<
  typeof PostOrganizationAddMembersBody
>;
export type PostOrganizationAddMembersBodyOutput = zod.output<
  typeof PostOrganizationAddMembersBody
>;
