/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import { z as zod } from 'zod';

export const PostAuthRefresh404 = zod
  .object({
    success: zod.literal(false),
    data: zod.unknown().nullable(),
    error: zod.object({
      code: zod.string(),
      details: zod.unknown().optional(),
    }),
    meta: zod.object({
      unixTimestamp: zod.number(),
      requestId: zod.string().optional(),
    }),
  })
  .describe('Session Not Found');

export type PostAuthRefresh404 = zod.input<typeof PostAuthRefresh404>;
export type PostAuthRefresh404Output = zod.output<typeof PostAuthRefresh404>;
