/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import { z as zod } from 'zod';

export const PostAuthSignOut200 = zod.object({
  success: zod.literal(true),
  data: zod.object({}),
  error: zod.unknown().nullable(),
  meta: zod.object({
    unixTimestamp: zod.number(),
    requestId: zod.string().optional(),
  }),
});

export type PostAuthSignOut200 = zod.input<typeof PostAuthSignOut200>;
export type PostAuthSignOut200Output = zod.output<typeof PostAuthSignOut200>;
