/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import { z as zod } from 'zod';

export const postAuthRefresh200DataUserIdRegExp = new RegExp(
  '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$',
);
export const postAuthRefresh200DataUserEmailRegExp = new RegExp(
  "^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$",
);

export const PostAuthRefresh200 = zod.object({
  success: zod.literal(true),
  data: zod.object({
    accessToken: zod.string(),
    refreshToken: zod.string(),
    user: zod.object({
      id: zod.uuid().regex(postAuthRefresh200DataUserIdRegExp),
      email: zod.string().regex(postAuthRefresh200DataUserEmailRegExp),
      name: zod.string(),
    }),
  }),
  error: zod.unknown().nullable(),
  meta: zod.object({
    unixTimestamp: zod.number(),
    requestId: zod.string().optional(),
  }),
});

export type PostAuthRefresh200 = zod.input<typeof PostAuthRefresh200>;
export type PostAuthRefresh200Output = zod.output<typeof PostAuthRefresh200>;
