/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import { z as zod } from 'zod';

export const PostOrganizationAddMembers409 = zod
  .object({
    success: zod.literal(false),
    data: zod.unknown().nullable(),
    error: zod.object({
      code: zod.string(),
      details: zod.unknown().optional(),
    }),
    meta: zod.object({
      unixTimestamp: zod.number(),
      requestId: zod.string().optional(),
    }),
  })
  .describe('Member already exists in the organization');

export type PostOrganizationAddMembers409 = zod.input<
  typeof PostOrganizationAddMembers409
>;
export type PostOrganizationAddMembers409Output = zod.output<
  typeof PostOrganizationAddMembers409
>;
