/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import { z as zod } from 'zod';

export const postAuthSignInBodyEmailRegExp = new RegExp(
  "^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$",
);

export const PostAuthSignInBody = zod.object({
  email: zod.string().regex(postAuthSignInBodyEmailRegExp),
  password: zod.string(),
});

export type PostAuthSignInBody = zod.input<typeof PostAuthSignInBody>;
export type PostAuthSignInBodyOutput = zod.output<typeof PostAuthSignInBody>;
