/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import { z as zod } from 'zod';

export const PostAuthSignOutBody = zod.object({});

export type PostAuthSignOutBody = zod.input<typeof PostAuthSignOutBody>;
export type PostAuthSignOutBodyOutput = zod.output<typeof PostAuthSignOutBody>;
