/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import { z as zod } from 'zod';

export const PostAuthSignIn400 = zod
  .object({
    success: zod.literal(false),
    data: zod.unknown().nullable(),
    error: zod.object({
      code: zod.string(),
      details: zod.unknown().optional(),
    }),
    meta: zod.object({
      unixTimestamp: zod.number(),
      requestId: zod.string().optional(),
    }),
  })
  .describe('Invalid input or missing required fields');

export type PostAuthSignIn400 = zod.input<typeof PostAuthSignIn400>;
export type PostAuthSignIn400Output = zod.output<typeof PostAuthSignIn400>;
