/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import { z as zod } from 'zod';

export const postAuthSignUp201DataIdRegExp = new RegExp(
  '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$',
);

export const PostAuthSignUp201 = zod.object({
  success: zod.literal(true),
  data: zod.object({
    id: zod.uuid().regex(postAuthSignUp201DataIdRegExp),
  }),
  error: zod.unknown().nullable(),
  meta: zod.object({
    unixTimestamp: zod.number(),
    requestId: zod.string().optional(),
  }),
});

export type PostAuthSignUp201 = zod.input<typeof PostAuthSignUp201>;
export type PostAuthSignUp201Output = zod.output<typeof PostAuthSignUp201>;
