/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import { z as zod } from 'zod';

export const PostOrganizationAddMembers201 = zod.object({
  success: zod.literal(true),
  data: zod.object({
    message: zod.string(),
  }),
  error: zod.unknown().nullable(),
  meta: zod.object({
    unixTimestamp: zod.number(),
    requestId: zod.string().optional(),
  }),
});

export type PostOrganizationAddMembers201 = zod.input<
  typeof PostOrganizationAddMembers201
>;
export type PostOrganizationAddMembers201Output = zod.output<
  typeof PostOrganizationAddMembers201
>;
