/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import { z as zod } from 'zod';

export const postAuthSignUpBodyNameMin = 2;
export const postAuthSignUpBodyNameMax = 20;

export const postAuthSignUpBodyEmailRegExp = new RegExp(
  "^(?!\\.)(?!.*\\.\\.)([A-Za-z0-9_'+\\-\\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$",
);

export const PostAuthSignUpBody = zod.object({
  name: zod
    .string()
    .min(postAuthSignUpBodyNameMin)
    .max(postAuthSignUpBodyNameMax),
  email: zod.string().regex(postAuthSignUpBodyEmailRegExp),
  password: zod.string(),
});

export type PostAuthSignUpBody = zod.input<typeof PostAuthSignUpBody>;
export type PostAuthSignUpBodyOutput = zod.output<typeof PostAuthSignUpBody>;
