/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import { z as zod } from 'zod';

export const PostOrganizationAddMembers403 = zod
  .object({
    success: zod.literal(false),
    data: zod.unknown().nullable(),
    error: zod.object({
      code: zod.string(),
      details: zod.unknown().optional(),
    }),
    meta: zod.object({
      unixTimestamp: zod.number(),
      requestId: zod.string().optional(),
    }),
  })
  .describe('Member cannot be added to this organization');

export type PostOrganizationAddMembers403 = zod.input<
  typeof PostOrganizationAddMembers403
>;
export type PostOrganizationAddMembers403Output = zod.output<
  typeof PostOrganizationAddMembers403
>;
