/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import { z as zod } from 'zod';

export const PostAuthRefreshBody = zod.object({});

export type PostAuthRefreshBody = zod.input<typeof PostAuthRefreshBody>;
export type PostAuthRefreshBodyOutput = zod.output<typeof PostAuthRefreshBody>;
