/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import { z as zod } from 'zod';

export const PostOrganizationBody = zod.object({
  title: zod.string(),
});

export type PostOrganizationBody = zod.input<typeof PostOrganizationBody>;
export type PostOrganizationBodyOutput = zod.output<
  typeof PostOrganizationBody
>;
